apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: causely
  namespace: causely
spec:
  interval: 1h
  chart:
    spec:
      chart: causely
      version: v1.0.97-0-gf71047ab64214ce4
      sourceRef:
        kind: HelmRepository
        name: causely
        namespace: causely
  values:
    global:
      cluster_name: production

    image:
      tag: v1.0.97-0-gf71047ab64214ce4

    mediator:
      gateway:
        token: "ABCSDFGHIJKLMNOPQRSTUVWXYZ"
